name: Build and Release Firmware

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  gh-pages-update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch for index.html
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Copy index.html to gh-pages branch
        run: |
          cp index.html /tmp/index.html

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Replace index.html
        run: |
          rm -f index.html
          cp /tmp/index.html .

      - name: Commit and push index.html to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add index.html  # Fixed the filename here
          git commit --amend --no-edit
          git push --force origin gh-pages

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get environments from platformio.ini
        id: get_envs
        run: |
          environments=$(grep -oP '^\s*\[env:\K[^\]]+' platformio.ini | tr '\n' ' ')
          echo "Environments: $environments"
          echo "envs=$environments" >> $GITHUB_ENV

      - name: Build firmware for all environments
        run: |
          environments=(${{ env.envs }})
          for env in "${environments[@]}"; do
            echo "Building for environment: $env"
            platformio run -e "$env"
          done

      - name: Run Semantic Release
        id: semantic_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release
          git tag -l --points-at HEAD
          echo "new_release_tag=v$(git tag -l --points-at HEAD)" >> $GITHUB_ENV

  deploy-fw-to-gh-pages:
    runs-on: ubuntu-latest
    needs: [build, gh-pages-update-html]
    if: success()
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Copy built binaries
        run: |
          mkdir -p firmware/${{ env.new_release_tag }}
          cp .pio/build/*/sbxm-firmware-*.bin firmware/${{ env.new_release_tag }}/

      - name: Commit and push binaries to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add firmware/${{ env.new_release_tag }}
          git commit --amend --no-edit
          git push --force origin gh-pages
