name: Build and Deploy Firmware to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install PlatformIO
        run: |
          python3 -m pip install -U platformio

      - name: Build firmware for Wemos D1 Mini 32
        run: platformio run --environment wemos_d1_mini32

      - name: Build firmware for ESP32-S3
        run: platformio run --environment esp32-s3-n16r8

      - name: Create firmware directory
        run: mkdir -p firmware

      - name: Run merge script and move binaries
        run: |
          cp .pio/build/wemos_d1_mini32/merged-firmware.bin firmware/firmware_wemos_d1_mini32.bin
          cp .pio/build/esp32-s3-n16r8/merged-firmware.bin firmware/firmware_esp32_s3_n16r8.bin

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./firmware
